version: '3.7'
services:
  certbot:
    image: certbot/dns-ovh:latest
    restart: 'no'
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./ovh.ini:/etc/letsencrypt/ovh.ini
    environment:
      DEPLOY_DOMAIN: ${DEPLOY_DOMAIN}
      DEPLOY_EMAIL: ${DEPLOY_EMAIL}
    entrypoint: 'certbot certonly
      -d ${DEPLOY_DOMAIN}
      --email=${DEPLOY_EMAIL}
      --agree-tos
      --non-interactive
      --dns-ovh
      --dns-ovh-propagation-seconds=10
      --dns-ovh-credentials=/etc/letsencrypt/ovh.ini'
  nginx:
    image: nginx:latest
    environment:
      LE_PATH: ${LE_PATH}
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx/ssl-proxy.conf:/etc/nginx/templates/default.conf.template
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend-frontend
      - certbot
volumes:
  letsencrypt: