version: '3.7'
services:
  backend-frontend:
    build: backend-frontend
    image: backend-frontend:latest
    env_file: backend-frontend/.env
    environment:
      - DATABASE_URL=rethinkdb://db:28015/production
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: rethinkdb:2.4
    volumes:
      - db-data:/data
    ports:
      - 8080:8080
volumes:
  db-data:
