version: '3.7'
services:
  backend-frontend:
    restart: unless-stopped
    image: backend-frontend:${BUILD_TAG:-latest}
    environment:
      DATABASE_URL: rethinkdb://db:28015/${DATABASE_NAME:-test}
      PORT: 80
      VAPID_SUBJECT: ${VAPID_SUBJECT}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
    depends_on:
      - db
  db:
    restart: unless-stopped
    image: rethinkdb:2.4
    volumes:
      - db-data:/data
  ssl:
    restart: unless-stopped
    image: ssl:${BUILD_TAG:-latest}
    ports:
      - 80:80
      - 443:443
    environment:
      APP_URL: http://backend-frontend
    depends_on:
      - backend-frontend
volumes:
  db-data:
